In [30]:
# dataset from https://oracleselixir.com/
# https://drive.google.com/drive/u/1/folders/1gLSw0RLjBbtaNy0dgnGQDAZOHIgCe-HH

import pandas as pd

file_name = '2023_LoL_esports_match_data_from_OraclesElixir.csv'

df = pd.read_csv(file_name)

df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_26296\856557456.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,212.0,1356.0,891.0,32.0,0.0,0.0,0.0,0.0,1.0,0.0
1,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,172.0,23.0,-932.0,-53.0,0.0,0.0,1.0,0.0,1.0,0.0
2,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,245.0,-264.0,-1191.0,-24.0,0.0,0.0,0.0,1.0,0.0,0.0
3,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,220.0,470.0,682.0,14.0,0.0,0.0,0.0,1.0,1.0,0.0
4,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,4.0,-47.0,-476.0,8.0,0.0,0.0,1.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131671,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131672,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131673,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131674,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131675,10659-10659_game_4,partial,https://lpl.qq.com/es/stats.shtml?bmid=10659,DCup,2023,NaN,0,2023-12-31 11:48:06,4,13.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
print(list(df.keys()))

['gameid', 'datacompleteness', 'url', 'league', 'year', 'split', 'playoffs', 'date', 'game', 'patch', 'participantid', 'side', 'position', 'playername', 'playerid', 'teamname', 'teamid', 'champion', 'ban1', 'ban2', 'ban3', 'ban4', 'ban5', 'pick1', 'pick2', 'pick3', 'pick4', 'pick5', 'gamelength', 'result', 'kills', 'deaths', 'assists', 'teamkills', 'teamdeaths', 'doublekills', 'triplekills', 'quadrakills', 'pentakills', 'firstblood', 'firstbloodkill', 'firstbloodassist', 'firstbloodvictim', 'team kpm', 'ckpm', 'firstdragon', 'dragons', 'opp_dragons', 'elementaldrakes', 'opp_elementaldrakes', 'infernals', 'mountains', 'clouds', 'oceans', 'chemtechs', 'hextechs', 'dragons (type unknown)', 'elders', 'opp_elders', 'firstherald', 'heralds', 'opp_heralds', 'void_grubs', 'opp_void_grubs', 'firstbaron', 'barons', 'opp_barons', 'firsttower', 'towers', 'opp_towers', 'firstmidtower', 'firsttothreetowers', 'turretplates', 'opp_turretplates', 'inhibitors', 'opp_inhibitors', 'damagetochampions', 'dpm', 'damageshare', 'damagetakenperminute', 'damagemitigatedperminute', 'wardsplaced', 'wpm', 'wardskilled', 'wcpm', 'controlwardsbought', 'visionscore', 'vspm', 'totalgold', 'earnedgold', 'earned gpm', 'earnedgoldshare', 'goldspent', 'gspd', 'gpr', 'total cs', 'minionkills', 'monsterkills', 'monsterkillsownjungle', 'monsterkillsenemyjungle', 'cspm', 'goldat10', 'xpat10', 'csat10', 'opp_goldat10', 'opp_xpat10', 'opp_csat10', 'golddiffat10', 'xpdiffat10', 'csdiffat10', 'killsat10', 'assistsat10', 'deathsat10', 'opp_killsat10', 'opp_assistsat10', 'opp_deathsat10', 'goldat15', 'xpat15', 'csat15', 'opp_goldat15', 'opp_xpat15', 'opp_csat15', 'golddiffat15', 'xpdiffat15', 'csdiffat15', 'killsat15', 'assistsat15', 'deathsat15', 'opp_killsat15', 'opp_assistsat15', 'opp_deathsat15', 'goldat20', 'xpat20', 'csat20', 'opp_goldat20', 'opp_xpat20', 'opp_csat20', 'golddiffat20', 'xpdiffat20', 'csdiffat20', 'killsat20', 'assistsat20', 'deathsat20', 'opp_killsat20', 'opp_assistsat20', 'opp_deathsat20', 'goldat25', 'xpat25', 'csat25', 'opp_goldat25', 'opp_xpat25', 'opp_csat25', 'golddiffat25', 'xpdiffat25', 'csdiffat25', 'killsat25', 'assistsat25', 'deathsat25', 'opp_killsat25', 'opp_assistsat25', 'opp_deathsat25']

In [32]:
# removing incomplete data
df = df.loc[df['datacompleteness'] == 'complete']
df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,212.0,1356.0,891.0,32.0,0.0,0.0,0.0,0.0,1.0,0.0
1,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,172.0,23.0,-932.0,-53.0,0.0,0.0,1.0,0.0,1.0,0.0
2,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,245.0,-264.0,-1191.0,-24.0,0.0,0.0,0.0,1.0,0.0,0.0
3,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,220.0,470.0,682.0,14.0,0.0,0.0,0.0,1.0,1.0,0.0
4,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,4.0,-47.0,-476.0,8.0,0.0,0.0,1.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131179,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,205.0,99.0,-2027.0,-22.0,1.0,3.0,3.0,1.0,5.0,4.0
131180,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,227.0,481.0,313.0,1.0,3.0,1.0,1.0,1.0,1.0,0.0
131181,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,26.0,2.0,-197.0,3.0,0.0,5.0,1.0,0.0,4.0,3.0
131182,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,834.0,-214.0,2590.0,-61.0,9.0,13.0,7.0,7.0,13.0,9.0
131183,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,773.0,214.0,-2590.0,61.0,7.0,13.0,9.0,9.0,13.0,7.0

In [33]:
# remove information about team
df = df.loc[df['position'] != 'team']
df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,212.0,1356.0,891.0,32.0,0.0,0.0,0.0,0.0,1.0,0.0
1,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,172.0,23.0,-932.0,-53.0,0.0,0.0,1.0,0.0,1.0,0.0
2,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,245.0,-264.0,-1191.0,-24.0,0.0,0.0,0.0,1.0,0.0,0.0
3,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,220.0,470.0,682.0,14.0,0.0,0.0,0.0,1.0,1.0,0.0
4,ESPORTSTMNT06_2753012,complete,NaN,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,...,4.0,-47.0,-476.0,8.0,0.0,0.0,1.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131177,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,215.0,-2414.0,-2243.0,-6.0,2.0,1.0,3.0,7.0,0.0,0.0
131178,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,100.0,2046.0,1564.0,85.0,1.0,3.0,1.0,0.0,3.0,0.0
131179,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,205.0,99.0,-2027.0,-22.0,1.0,3.0,3.0,1.0,5.0,4.0
131180,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,227.0,481.0,313.0,1.0,3.0,1.0,1.0,1.0,1.0,0.0
131181,ESPORTSTMNT01_3438981,complete,NaN,NEXO,2024,Split 1,0,2023-11-27 18:33:43,3,13.22,...,26.0,2.0,-197.0,3.0,0.0,5.0,1.0,0.0,4.0,3.0

In [34]:
df = df[['patch', 'side', 'position', 'playername', 'champion', 'gamelength', 'result', 'kills', 'deaths', 'assists', 'firstbloodkill', 'firstbloodassist', 'firstbloodvictim', 'ckpm', 'barons', 'opp_barons', 'inhibitors', 'opp_inhibitors', 'dpm', 'damagetakenperminute', 'damagemitigatedperminute', 'wpm', 'wcpm', 'vspm', 'earned gpm', 'cspm']]
df

,patch,side,position,playername,champion,gamelength,result,kills,deaths,assists,...,inhibitors,opp_inhibitors,dpm,damagetakenperminute,damagemitigatedperminute,wpm,wcpm,vspm,earned gpm,cspm
0,13.01,Blue,top,Wylenz,Jax,2612,1,4,0,6,...,1.0,0.0,328.0934,719.5406,878.9127,0.4594,0.1149,1.1256,304.3874,9.1654
1,13.01,Blue,jng,Julbu,Poppy,2612,1,2,2,4,...,0.0,0.0,142.8560,847.3047,1513.9663,0.4135,0.2527,1.4012,148.8055,3.6524
2,13.01,Blue,mid,Sintax,Taliyah,2612,1,2,2,11,...,0.0,0.0,620.8576,365.3522,323.7289,0.5283,0.2297,1.1256,232.4196,7.7412
3,13.01,Blue,bot,Axelent,Ezreal,2612,1,5,1,7,...,1.0,0.0,964.8928,398.4533,234.3721,0.3905,0.1378,1.0796,269.4028,8.4992
4,13.01,Blue,sup,Wixo,Karma,2612,1,0,2,10,...,0.0,0.0,130.1991,360.2757,284.1501,1.1945,0.1838,2.4349,73.7825,0.4824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131177,13.22,Red,top,Dani,Gnar,2144,0,2,3,1,...,0.0,0.0,649.4496,649.9254,509.1884,0.4198,0.0560,1.0634,230.4291,8.0597
131178,13.22,Red,jng,Emvipi,Graves,2144,0,2,3,3,...,0.0,0.0,373.4328,668.6754,440.1493,0.1119,0.2799,1.2593,211.2593,7.3881
131179,13.22,Red,mid,Nestor,Neeko,2144,0,1,5,4,...,0.0,1.0,416.2220,518.9552,258.0504,0.3918,0.1399,0.6716,187.5280,6.3246
131180,13.22,Red,bot,Kurilius,Ziggs,2144,0,4,1,1,...,0.0,1.0,801.0168,281.7817,149.3843,0.4757,0.0840,0.6996,257.7425,8.8153
131181,13.22,Red,sup,Whyx,Rell,2144,0,0,3,7,...,0.0,0.0,136.3433,509.5802,653.9832,1.5392,0.1679,2.7705,77.2948,0.9795

In [35]:
df = df.dropna(axis = 0)
df

,patch,side,position,playername,champion,gamelength,result,kills,deaths,assists,...,inhibitors,opp_inhibitors,dpm,damagetakenperminute,damagemitigatedperminute,wpm,wcpm,vspm,earned gpm,cspm
0,13.01,Blue,top,Wylenz,Jax,2612,1,4,0,6,...,1.0,0.0,328.0934,719.5406,878.9127,0.4594,0.1149,1.1256,304.3874,9.1654
1,13.01,Blue,jng,Julbu,Poppy,2612,1,2,2,4,...,0.0,0.0,142.8560,847.3047,1513.9663,0.4135,0.2527,1.4012,148.8055,3.6524
2,13.01,Blue,mid,Sintax,Taliyah,2612,1,2,2,11,...,0.0,0.0,620.8576,365.3522,323.7289,0.5283,0.2297,1.1256,232.4196,7.7412
3,13.01,Blue,bot,Axelent,Ezreal,2612,1,5,1,7,...,1.0,0.0,964.8928,398.4533,234.3721,0.3905,0.1378,1.0796,269.4028,8.4992
4,13.01,Blue,sup,Wixo,Karma,2612,1,0,2,10,...,0.0,0.0,130.1991,360.2757,284.1501,1.1945,0.1838,2.4349,73.7825,0.4824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131177,13.22,Red,top,Dani,Gnar,2144,0,2,3,1,...,0.0,0.0,649.4496,649.9254,509.1884,0.4198,0.0560,1.0634,230.4291,8.0597
131178,13.22,Red,jng,Emvipi,Graves,2144,0,2,3,3,...,0.0,0.0,373.4328,668.6754,440.1493,0.1119,0.2799,1.2593,211.2593,7.3881
131179,13.22,Red,mid,Nestor,Neeko,2144,0,1,5,4,...,0.0,1.0,416.2220,518.9552,258.0504,0.3918,0.1399,0.6716,187.5280,6.3246
131180,13.22,Red,bot,Kurilius,Ziggs,2144,0,4,1,1,...,0.0,1.0,801.0168,281.7817,149.3843,0.4757,0.0840,0.6996,257.7425,8.8153
131181,13.22,Red,sup,Whyx,Rell,2144,0,0,3,7,...,0.0,0.0,136.3433,509.5802,653.9832,1.5392,0.1679,2.7705,77.2948,0.9795

In [36]:
factorize_list = ['side', 'position', 'playername', 'champion']
values_list = []
for feature in factorize_list:
    df_feature, value_list = pd.factorize(df[feature])
    df.loc[:, feature] = df_feature
    values_list.append(value_list)

for feature_no in range(len(factorize_list)):
    print(f"{factorize_list[feature_no]}: {values_list[feature_no]}")

df

side: Index(['Blue', 'Red'], dtype='object')
position: Index(['top', 'jng', 'mid', 'bot', 'sup'], dtype='object')
playername: Index(['Wylenz', 'Julbu', 'Sintax', 'Axelent', 'Wixo', 'Anathar', 'nicolaiy',
       'Kuroneel', 'Scripter', 'Zimba',
       ...
       'Mounnika', 'Pake', 'Sabo', 'Zoro', 'Sanji', 'Hyo', 'Kwhite', 'K1ller',
       'PabloPedrolo', 'Lumos'],
      dtype='object', length=2823)
champion: Index(['Jax', 'Poppy', 'Taliyah', 'Ezreal', 'Karma', 'Sejuani', 'Viego',
       'Syndra', 'Zeri', 'Yuumi',
       ...
       'Neeko', 'Fiddlesticks', 'Aurelion Sol', 'Fizz', 'Evelynn', 'Milio',
       'Shaco', 'Quinn', 'Naafiri', 'Briar'],
      dtype='object', length=163)

,patch,side,position,playername,champion,gamelength,result,kills,deaths,assists,...,inhibitors,opp_inhibitors,dpm,damagetakenperminute,damagemitigatedperminute,wpm,wcpm,vspm,earned gpm,cspm
0,13.01,0,0,0,0,2612,1,4,0,6,...,1.0,0.0,328.0934,719.5406,878.9127,0.4594,0.1149,1.1256,304.3874,9.1654
1,13.01,0,1,1,1,2612,1,2,2,4,...,0.0,0.0,142.8560,847.3047,1513.9663,0.4135,0.2527,1.4012,148.8055,3.6524
2,13.01,0,2,2,2,2612,1,2,2,11,...,0.0,0.0,620.8576,365.3522,323.7289,0.5283,0.2297,1.1256,232.4196,7.7412
3,13.01,0,3,3,3,2612,1,5,1,7,...,1.0,0.0,964.8928,398.4533,234.3721,0.3905,0.1378,1.0796,269.4028,8.4992
4,13.01,0,4,4,4,2612,1,0,2,10,...,0.0,0.0,130.1991,360.2757,284.1501,1.1945,0.1838,2.4349,73.7825,0.4824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131177,13.22,1,0,2050,83,2144,0,2,3,1,...,0.0,0.0,649.4496,649.9254,509.1884,0.4198,0.0560,1.0634,230.4291,8.0597
131178,13.22,1,1,2046,48,2144,0,2,3,3,...,0.0,0.0,373.4328,668.6754,440.1493,0.1119,0.2799,1.2593,211.2593,7.3881
131179,13.22,1,2,255,153,2144,0,1,5,4,...,0.0,1.0,416.2220,518.9552,258.0504,0.3918,0.1399,0.6716,187.5280,6.3246
131180,13.22,1,3,196,40,2144,0,4,1,1,...,0.0,1.0,801.0168,281.7817,149.3843,0.4757,0.0840,0.6996,257.7425,8.8153
131181,13.22,1,4,1971,92,2144,0,0,3,7,...,0.0,0.0,136.3433,509.5802,653.9832,1.5392,0.1679,2.7705,77.2948,0.9795

In [37]:
output_file_name = 'preprocessed_' + file_name
df.to_csv(output_file_name, index=False)